name: "Mr.bone的小站"
des: "记录Mr.bone的点点滴滴"
permalink: pretty
paginate: 5
exclude: ['less','font-face']

custom:
  category: [demo,life]
  categories:
    - name: demo
      url: demo
    - name: "life"
      url: life

