name: "Mr.bone的小站"
des: "记录Mr.bone的点点滴滴"
permalink: pretty
paginate: 5
exclude: ['less']

custom:
  category: [demo,other]
  categories:
    - name: demo
      url: demo
    - name: "other"
      url: other

  